Controllers/AdminController.cs
using CakesShop.Models;
using CakesShop.Models.Interfaces;
using CakesShop.Models.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CakesShop.Controllers
{
    public class AdminController : Controller
    {
        private readonly ICake _cakeRepo;
        private readonly IWebHostEnvironment Environment;

      
        public AdminController(ICake _c, IWebHostEnvironment environment)
        {

            _cakeRepo = _c;
            Environment = environment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddProduct(Cake c, IFormFile postedFiles)
        {
            string wwwPath = this.Environment.WebRootPath;

            string path = Path.Combine(wwwPath, "Uploads");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
             var fileName = Path.GetFileName(postedFiles.FileName);
                var pathWithFileName = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(pathWithFileName, FileMode.Create))
                {
                postedFiles.CopyTo(stream);
                    ViewBag.Message = "file uploaded successfully";
                }

            //Cake c1 = new Cake();
            //c1 = c;
            string imgpath = "/Uploads/" +postedFiles.FileName;
            c.Image = imgpath;

                _cakeRepo.Add_cake(c);
                return View();
        }


        [Route("cake-update/{id:int:min(1)}", Name = "cakeupdateroot")]
        public async Task<ViewResult> UpdateProduct(int id)
        {
            Cake data = _cakeRepo.GetCakeById(id);

            return View(data);
        }

        [Route("cake-updatepost/{id:int:min(1)}", Name = "cakeupdaterootpost")]
        public IActionResult UpdateProduct(int id,Cake c,IFormFile postedFiles)
        {
           
            Cake data = _cakeRepo.GetCakeById(id);
            data.Price = c.Price;
            data.Category = c.Category;
            data.Description = c.Description;
            data.Pond = c.Pond;
            if (postedFiles != null)
            {
                deleteUploadImge(id);
                string wwwPath = this.Environment.WebRootPath;
                string path = Path.Combine(wwwPath, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                var fileName = Path.GetFileName(postedFiles.FileName);
                var pathWithFileName = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(pathWithFileName, FileMode.Create))
                {
                    postedFiles.CopyTo(stream);
                    ViewBag.Message = "file uploaded successfully";
                }


                string imgpath = "/Uploads/" + postedFiles.FileName;
                data.Image = imgpath;
            }
           

            _cakeRepo.UpdateCake(data);

            return View("Index");
        }





        public IActionResult Addimg()
        {
            return View();
        }
        
        
        
        
        [HttpPost]
        
        
        public IActionResult Addimg(List<IFormFile> postedFiles)
        {
            string wwwPath = this.Environment.WebRootPath;

            string path = Path.Combine(wwwPath, "Uploads");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            foreach (var file in postedFiles)
            {
                var fileName = Path.GetFileName(file.FileName);
                var pathWithFileName = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(pathWithFileName, FileMode.Create))
                {
                    file.CopyTo(stream);
                    ViewBag.Message = "file uploaded successfully";
                }
            }
            return View();
        }
        public void deleteUploadImge(int id)
        {
            Cake data = _cakeRepo.GetCakeById(id);
            string wwwPath = this.Environment.WebRootPath;

            string path = Path.Combine(wwwPath, "Uploads");
            string img = data.Image;
            var pathWithFileName = Path.Combine(path, img);
            System.IO.File.Delete(pathWithFileName);
        }
    }
}

Controllers/UserController.cs
using CakesShop.Models;
using Microsoft.AspNetCore.Mvc;
using CakesShop.Models.Interfaces;
using System.Reflection.Metadata;
using System;
using AutoMapper;

namespace CakesShop.Controllers
{
    public class UserController : Controller
    {

        private readonly IUser _userRepo;
        private readonly IMapper _mapper;
        public UserController(IUser _user, IMapper mapper)
        {

            _userRepo = _user;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Signup()
        {
            return View();
        }
       
        [HttpPost]
        public IActionResult Signup( User u)
        {
            if (u.Password!=null && u.Name!=null) { 
               

            _userRepo.Add_User(u);

               return View("Home");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(User u)
        {
            string data = String.Empty;
            if (HttpContext.Session.Keys.Contains("SessionCreate"))
            {
                string firsttime = HttpContext.Session.GetString("SessionCreate");
                data = "welcome back" + firsttime;
            }
            else
            {
                data = "You visit first time";
                HttpContext.Session.SetString("SessionCreate", System.DateTime.Now.ToString());
            }

            bool i= _userRepo.UserExist(u);
            if (i)
                return View("Home");
            else
                return View();

        }


        public IActionResult Logout()
        {
            HttpContext.Session.Remove("SessionCreate");
            return View("Home");
        }
        [HttpGet]
        public IActionResult Home()
        {
            string data = String.Empty;
            if (HttpContext.Session.Keys.Contains("first_request"))
            {
                string firsttime = HttpContext.Session.GetString("first_request");
                data = "welcome back" + firsttime;
            }
            else
            {
                data = "You visit first time";
                HttpContext.Session.SetString("first_request", System.DateTime.Now.ToString());
            }
            
            return View();
        }
        public IActionResult remove()
        {
            HttpContext.Session.Remove("first_request");
            return View("Home");
        }
        [HttpGet]
        public IActionResult Items()
        {

            return View();
        }
        [HttpGet]
        public IActionResult BreakFast_Lunch()
        {

            return View();
        }
        [HttpGet]
        public IActionResult Drink()
        {

            return View();
        }
        [HttpGet]
        public IActionResult Contact()
        {

            return View();
        }
        public PartialViewResult Add()
        {
            User u = new User();
            u.Name = "aaa";
            u.Password = "133";
            return PartialView("viewdata", u);
        }

      
    }
}

Views/Shared/Products_admin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="card mb-4 shadow-sm items ">
   
    <div class="card-body ">
        <img src="/images/c2.png" class="img-thumbnail"  >
        <h3 class="card-title">cake</h3>
        <p class="card-text">choclate</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a class="btn btn-sm btn-solid-lg" style="background-color: #bdd4e7;
background-image: linear-gradient(315deg, #bdd4e7 0%, #8693ab 74%);
">Edit</a>
                
            </div>
           <small class="text-muted">Delete/</small>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    @*<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">




    <link href="~/css/site.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CakesOrder</title>


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/CakesOrder.styles.css" asp-append-version="true" />



</head>
<body>


    <nav class="navbar navbar-expand-lg fixed-top navbar-light navbarr" style="background-image: linear-gradient(135deg, #fdfcfb 0%, #e2d1c3 100%);">
        <div class="container-fluid">
            <a class="navHead">Online Cakes Order</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <div class="mid_navbar">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="User" asp-action="Home">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class=" nav-link " asp-controller="User" asp-action="Items">ORDER_ONLINE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="User" asp-action="Contact">CONTACT</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle menuLi" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                MENU
                            </a>
                            <ul class="dropdown-menu menuU" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="User" asp-action="BreakFast_Lunch">BREAKFAST & LUNCH</a></li>
                                <li><a class="dropdown-item" asp-controller="User" asp-action="Drink">DRINKS</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="User" asp-action="Items">CAKES</a></li>
                            </ul>
                        </li>


                    </ul>

                </div>
                <a class="login" asp-controller="User" asp-action="Signup"> SIGNUP | </a>
                <a class="login" asp-controller="User" asp-action="Login">LOGIN</a>

                <a class="login" asp-controller="Admin" asp-action="Index">LoginAsAdmin</a>
            </div>
        </div>
    </nav>

    <div class="containerMain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

</body>
<!-- Footer -->
<footer class="page-footer bottom font-small pt-4 navbar-light bg-light" style="background: linear-gradient(135deg,#b0dae6,#ffd6c7 60%,#ffd6c7);">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-6 mt-md-0 mt-3 ">

                <!-- Content -->
                <h5 class="text-uppercase">Online Cakes  </h5>
                <p>H#136 Usman ghani street alhamd colony Iqbal town lahore </p>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

                <!-- Links -->

                <ul class="list-unstyled">
                    <li>
                        <a href="#!" style="color:black;">Online Order</a>
                    </li>
                    <li>
                        <a href="#!" style="color:black;">About</a>
                    <li>
                        <a href="#!" style="color:black;">Wedding and custom </a>
                    </li>
                    <li>
                        <a href="#!" style="color:black;">Contact</a>
                    </li>
                </ul>

            </div>

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

                <!-- Links -->
                <form>
                    <div>
                        <input type="text" class="form-control form-control-sm" placeholder="Your email"
                               aria-label="Your email" aria-describedby="basic-addon2">
                    </div>
                    <div class="input-group-append">
                        <button class="btn btn-secondary btn-outline-white my-0" type="button">Join Now</button>
                    </div>
                </form>


            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
        © 2020 Copyright:
        <a href="/"> SAC's.com</a>
    </div>
    <!-- Copyright -->
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
</html>

Views/Shared/_add.cshtml
<!DOCTYPE html>
<html lang="en">
<head>


</head>
<body>
  @RenderBody()
   
</body>
</html>

Views/Shared/_adminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


 @*<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">*@
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">




<link href="~/css/site.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - admin</title>


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="~/CakesOrder.styles.css" asp-append-version="true" />



</head>
<body>


<nav class="navbar navbar-expand-lg fixed-top navbar-light navbarr" style="background-image: linear-gradient(135deg, #fdfcfb 0%, #e2d1c3 100%);">
  <div class="container-fluid">
    <a class="navHead">Product Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
             aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
      <div class="mid_navbar">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item2 ">
             <a class="nav-link active" asp-controller="User" asp-action="Home">
                 Items
                 @*   <i class="fa fa-stack-exchange icon" style="font-size:30px;"></i>*@
                            </a>
             </li>


        <li class="nav-item2">
            
                
          <a class=" nav-link " asp-controller="Admin" asp-action="addproduct">
              Add Product
                               @* <i class="fa fa-shopping-cart icon" style="font-size:30px;"></i>*@
                            </a>
        </li>
        <li class="nav-item2">
           
          <a class="nav-link " asp-controller="Admin" asp-action="Item" >

                              @*  <i class="fa fa-user-circle-o icon" style="font-size:30px;"></i>*@
                            </a>
        </li>
        @* <li class="nav-item2 dropdown">
            
         <a class="nav-link dropdown-toggle menuLi" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
         <i class="fa fa-cogs icon" style="font-size:30px;"></i>
                            </a>
          <ul class="dropdown-menu menuU" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item"  asp-controller="User" asp-action="BreakFast_Lunch" >BREAKFAST & LUNCH</a></li>
            <li><a class="dropdown-item" asp-controller="User" asp-action="Drink">DRINKS</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" asp-controller="User" asp-action="Items">CAKES</a></li>
          </ul>
        </li>
       *@
        
      </ul>
      
      </div>
      
      <i class="fa fa-bell notify2" style="font-size:30px;"></i>
     <a class="logout2" asp-controller="User" asp-action="Login">LOGOUT</a>
  
    </div>
  </div>
</nav>
   <div class="">
        <main role="main" class="main2">
            @RenderBody()
        </main>
    </div>

</body>
 <!-- Footer -->
<footer class="page-footer bottom font-small pt-4 navbar-light bg-light"  style="background: linear-gradient(135deg,#b0dae6,#ffd6c7 60%,#ffd6c7);" >

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3 ">

        <!-- Content -->
        <h5 class="text-uppercase">Online Cakes  </h5>
        <p>H#136 Usman ghani street alhamd colony Iqbal town lahore </p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        
        <ul class="list-unstyled">
          <li>
            <a href="#!" style="color:black;">Online Order</a>
          </li>
          <li>
            <a href="#!"  style="color:black;">About</a>
          <li>
            <a href="#!"  style="color:black;">Wedding and custom </a>
          </li>
          <li>
            <a href="#!"  style="color:black;">Contact</a>
          </li>
        </ul>

      </div>

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
      <form >
         <div> <input type="text" class="form-control form-control-sm" placeholder="Your email"
            aria-label="Your email" aria-describedby="basic-addon2"></div>
          <div class="input-group-append">
            <button class="btn btn-secondary btn-outline-white my-0" type="button">Join Now</button>
          </div>
        </form>


      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> SAC's.com</a>
  </div>
  <!-- Copyright -->
</footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</html>

Views/Shared/addproduct.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/viewdata.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model User
<div>
    <table>
        <tr><td>@Model.Name</td></tr>
        <tr><td>@Model.Password</td></tr>

    </table>
</div>